//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Deserialize)]
#[sea_orm(table_name = "app")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub company_url: Option<String>,
    #[sea_orm(ignore, column_type = "custom(\"date\")", select_as = "text", nullable)]
    pub release_date: Option<String>,
    pub genre_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub artwork_large_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub seller_name: Option<String>,
    pub five_star_ratings: Option<i64>,
    pub four_star_ratings: Option<i64>,
    pub three_star_ratings: Option<i64>,
    pub two_star_ratings: Option<i64>,
    pub one_star_ratings: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::app_sdk::Entity")]
    AppSdk,
}

impl Related<super::app_sdk::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppSdk.def()
    }
}

impl Related<super::sdk::Entity> for Entity {
    fn to() -> RelationDef {
        super::app_sdk::Relation::Sdk.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::app_sdk::Relation::App.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
