//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Deserialize)]
#[sea_orm(table_name = "app_sdk")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub app_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub sdk_id: i64,
    pub installed: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app::Entity",
        from = "Column::AppId",
        to = "super::app::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    App,
    #[sea_orm(
        belongs_to = "super::sdk::Entity",
        from = "Column::SdkId",
        to = "super::sdk::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Sdk,
}

impl Related<super::app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::App.def()
    }
}

impl Related<super::sdk::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sdk.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
