//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Deserialize)]
#[sea_orm(table_name = "sdk")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub slug: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::app_sdk::Entity")]
    AppSdk,
}

impl Related<super::app_sdk::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppSdk.def()
    }
}

impl Related<super::app::Entity> for Entity {
    fn to() -> RelationDef {
        super::app_sdk::Relation::App.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::app_sdk::Relation::Sdk.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
